# Generated by Django 5.1.3 on 2024-11-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produtos', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produtos', models.CharField(max_length=140)),
                ('preco_produtos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao_produtos', models.CharField(max_length=255)),
                ('quantidade_de_variacao', models.IntegerField()),
                ('categoria_produtos', models.CharField(max_length=140)),
                ('data_de_iniciacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='produtos.produtos')),
            ],
        ),
    ]
