# Generated by Django 5.1.3 on 2024-11-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_imagemprodutos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemprodutos',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
