# Generated by Django 5.0.8 on 2024-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero_casa', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
