# Generated by Django 5.1 on 2024-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default=12345678, max_length=100),
            preserve_default=False,
        ),
    ]
