# Generated by Django 5.1 on 2024-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0002_usuario_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produtos', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_produto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=120)),
                ('condicao', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
