# Generated by Django 5.1.1 on 2024-11-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0003_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
