# Generated by Django 5.1 on 2024-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.TextField(max_length=255)),
            ],
        ),
    ]
