# Generated by Django 5.0.8 on 2024-08-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
