# Generated by Django 5.0.8 on 2024-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.TextField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_casa',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.TextField(default=1234567, max_length=255),
            preserve_default=False,
        ),
    ]
