# Generated by Django 5.0.8 on 2024-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0004_remove_usuario_bairro_remove_usuario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='complemento',
            field=models.TextField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
