# Generated by Django 5.0.8 on 2024-08-26 18:56

import Loja_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0005_localizacao_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(max_length=255),
        ),
    ]
