# Generated by Django 5.0.8 on 2024-08-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0006_alter_usuario_nome_alter_usuario_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacao',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
