# Generated by Django 5.0.8 on 2024-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_app', '0008_rename_id_usuario_localizacao_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacao',
            old_name='numero_casa',
            new_name='locradouro',
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
